#requires -Version 5.1
<#
.SYNOPSIS
Install this checkout and generate a local Codex MCP configuration snippet.
.DESCRIPTION
Uses the project's .venv-codex. Does not install Codex or STAAD.Pro and does not edit
the user's Codex settings. Re-running refreshes the installation and snippet.
.PARAMETER Python
Python 3.11+ executable used when creating a new virtual environment.
.PARAMETER AllowedDirectories
Existing directories for CSV/XLSX access. Defaults to the project directory.
.PARAMETER Dev
Include the project's development dependencies.
#>
[CmdletBinding()]
param(
    [string]$Python = 'python',
    [string[]]$AllowedDirectories = @(),
    [switch]$Dev
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Invoke-CheckedCommand {
    param([string]$Executable, [string[]]$CommandArguments)
    & $Executable @CommandArguments
    if ($LASTEXITCODE -ne 0) {
        throw "Command failed (exit $LASTEXITCODE): $Executable"
    }
}

try {
    if ($env:OS -ne 'Windows_NT') {
        throw 'OpenSTAAD requires Windows and a local STAAD.Pro installation.'
    }

    $projectDirectory = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).ProviderPath
    $ptcSource = Join-Path $projectDirectory 'src\openstaad_mcp\ptc\adapter.py'
    if (-not (Test-Path -LiteralPath $ptcSource -PathType Leaf)) {
        throw 'This checkout does not contain PTC. Use a PTC-V1 checkout containing the PTC source files.'
    }

    if ($AllowedDirectories.Count -eq 0) {
        $AllowedDirectories = @($projectDirectory)
    }
    $resolvedDirectories = @(
        foreach ($directory in $AllowedDirectories) {
            if (-not (Test-Path -LiteralPath $directory -PathType Container)) {
                throw "Allowed directory does not exist: $directory"
            }
            (Resolve-Path -LiteralPath $directory).ProviderPath
        }
    )

    $venvDirectory = Join-Path $projectDirectory '.venv-codex'
    $venvPython = Join-Path $venvDirectory 'Scripts\python.exe'
    $versionCheck = "import sys; sys.exit(0 if sys.version_info >= (3, 11) else 'Python 3.11 or newer is required')"
    if (-not (Test-Path -LiteralPath $venvPython -PathType Leaf)) {
        Invoke-CheckedCommand $Python @('-c', $versionCheck)
        Invoke-CheckedCommand $Python @('-m', 'venv', $venvDirectory)
    }
    Invoke-CheckedCommand $venvPython @('-c', $versionCheck)

    $serverExecutable = Join-Path $venvDirectory 'Scripts\openstaad-mcp.exe'
    if (Test-Path -LiteralPath $serverExecutable -PathType Leaf) {
        try {
            $probe = [System.IO.File]::Open($serverExecutable, 'Open', 'ReadWrite', 'None')
            $probe.Dispose()
        }
        catch {
            throw 'The server executable is in use. Stop this MCP server in its client before reinstalling.'
        }
    }

    $installTarget = $projectDirectory
    if ($Dev) {
        $installTarget = "$projectDirectory[dev]"
    }
    Invoke-CheckedCommand $venvPython @('-m', 'pip', 'install', '-e', $installTarget)
    Invoke-CheckedCommand $venvPython @('-m', 'pip', 'check')

    Invoke-CheckedCommand $venvPython @('-m', 'openstaad_mcp.main', '--help')
    $validateDirectories = 'import sys; from openstaad_mcp.file_io import validate_args_allowed_dirs; validate_args_allowed_dirs(sys.argv[1:])'
    Invoke-CheckedCommand $venvPython (@('-c', $validateDirectories) + $resolvedDirectories)
    $checkCatalog = "from openstaad_mcp.ptc.adapter import build_registry; catalog = build_registry().discover(); assert catalog, 'PTC catalog is empty'; print('PTC queries:', len(catalog))"
    Invoke-CheckedCommand $venvPython @('-c', $checkCatalog)

    # JSON string escaping is compatible with TOML basic strings for these paths.
    $commandToml = ConvertTo-Json -InputObject $venvPython -Compress
    $cwdToml = ConvertTo-Json -InputObject $projectDirectory -Compress
    $argumentsToml = ConvertTo-Json -InputObject (@('-m', 'openstaad_mcp.main', '--allowed-dirs') + $resolvedDirectories) -Compress
    $snippet = @"
# Generated by scripts/install-codex.ps1. Review before adding to Codex settings.
[mcp_servers.openstaad-ptc]
command = $commandToml
args = $argumentsToml
cwd = $cwdToml
startup_timeout_sec = 30
tool_timeout_sec = 180
"@
    $snippetPath = Join-Path $venvDirectory 'openstaad-codex.toml'
    [System.IO.File]::WriteAllText($snippetPath, $snippet + [Environment]::NewLine, [System.Text.UTF8Encoding]::new($false))
    $checkToml = "import pathlib, sys, tomllib; config = tomllib.loads(pathlib.Path(sys.argv[1]).read_text(encoding='utf-8')); assert 'openstaad-ptc' in config['mcp_servers']"
    Invoke-CheckedCommand $venvPython @('-c', $checkToml, $snippetPath)

    Write-Host "Installation verified. Codex configuration snippet: $snippetPath"
    Write-Host 'Review the snippet and merge its server table into your Codex config.toml.'
    Write-Host 'If openstaad-ptc already exists, update that table instead of adding a duplicate.'
    Write-Host 'Restart the MCP server in Codex after updating settings.'
}
catch {
    Write-Error -Message $_.Exception.Message -ErrorAction Continue
    exit 1
}
